# Functions


# function calls

### In the context of programming, a function is a named sequence of statements that performs a computation. When you define a function, you specify the name and the sequence of statements. Later, you can 'call' the function by name. 

In [5]:
# function call

print type(32)
print type('string')

# The name of the function is 'type'. The expression in parentheses is called the 'argument' of the function.
# It is common to say that a function 'takes' an argument and 'returns' a result. The result is called the 'return value'.

<type 'int'>
<type 'str'>


## Built-in functions

### Python provides a number of important built-in functions that we can use without needing to provide the function definition.

In [9]:
print max('HelloWorld!')
print min('HelloWorld!')
print len('HelloWorld!')

r
!
11


# Type conversion functions

### Python also provides built-in functions that convert values from one type to another.

In [20]:
print int('32')
print int(32)
print int(32.0)
print

print float(32)
print float('32')
print float('32.14')
print float(32.14)



32
32
32

32.0
32.0
32.14
32.14


# Random numbers

In [22]:
import random

# This program produces the list of 10 random numbers between 0.0 and up to but not includeing 1.0
for i in range(10):
    print random.random()

0.45019730202
0.926038214208
0.347652651514
0.397709669299
0.919215367632
0.262528013438
0.223421382509
0.970402598227
0.921079063008
0.158845007616


In [30]:
# random between 0 and 10
random.randint(0,10)

4

In [39]:
# To choose an element from a sequence at random, you can use 'choice'
num = [1, 2, 3]
text = ['test', 'name', 'surprise']

print random.choice(num)
print random.choice(text)

1
surprise


In [65]:
# This program produces the list of 10 random numbers between 0 and up to 9
for i in range(10):
    print int(random.random()*10)

2
0
1
9
2
5
6
0
2
1


In [56]:
# exercise

# Program produces the list of 5 random numbers between 1 and 10




In [63]:
# This program produces the list of 10 random numbers between 0 and 10
for i in range(10):    
    print random.randint(0,10)

5
0
8
0
3
6
6
0
5
6


# Adding new functions
### using the 'def statement is the most common way to define a function in python

In [ ]:
# defining and calling simple functions

def greet():
    print('Hello World!!!')

In [7]:
# call the defined function
greet()

Hello World!!!


In [8]:
# a function definition which takes one single argument

def greet(greeting):
    print(greeting)

In [9]:
# function must be called with an argument
greet('Hello World!!!')

Hello World!!!


In [11]:
# give a default value to a function argument

def greet(greeting='Hello World!!!'):
    print(greeting)

In [13]:
greet()

greet('Hi')

Hello World!!!
Hi


# Return

### Python functions can return values of any type via the 'return' keyword.

In [17]:
def many_types(x):
    if x > 0:
        return 'Hello!!!'
    else:
        return 0

In [18]:
print(many_types(1))
print(many_types(-1))

Hello!!!
0


## Defining a function with an arbitrary number of arguments 

In [68]:
def func(*args):
    for i in args:
        print(i)

In [73]:
func(1)
print

func(1,2,3,4,5)

1

1
2
3
4
5


In [75]:
list_of_arg_values = [1,2,'test']

func(*list_of_arg_values)
print

func(list_of_arg_values)

1
2
test

[1, 2, 'test']


In [76]:
# no output
func()

# Arguments

### An argument is a value we pass into the function as its input when we call the function
### We use arguments so we can direct the function to do different kinds of work when we call it at different times
### We put the arguments in parentheses after the name of the function


```
    max_value = max('Hello World')
```
'Hello World' = argument

# Parameters

### A parameter is a variable which we use in the function definition.
### It is a handle that allows the code in the function to access the arguments for a particular function invocation.

```
def greet(lang):
    if lang == 'es':
        print 'Hola'
    elif lang == 'fr':
        print 'Bonjour'
    else:
        print 'Hello'

```

'lang' = parameter

In [78]:
def greet(lang):
    if lang == 'es':
        print 'Hola'
    elif lang == 'fr':
        print 'Bonjour'
    else:
        print 'Hello'

greet('en')
greet('fr')
greet('es')

Hello
Bonjour
Hola


# Return values

### Often a function will take its arguments, do some computation, and 'return' a value to be used as the value of the function call in the calling expression. The 'return' keyword is used for this.

In [79]:
def greet():
    return 'Hello'

print greet(), 'Helen'
print greet(), 'Henderson'

Hello Helen
Hello Henderson


In [16]:
# a 'fruitful' function is one that produces a 'result' (or return value)
# The 'return' statement ends the function execution and 'sends back' the result of the function

def greet(lang):
    if lang == 'es':
        return 'Hola'
    elif lang == 'fr':
        return 'Bonjour'
    else:
        return 'Hello'

print greet('en'), 'Helen'
print greet('fr'), 'Henderson'
print greet('es'), 'Michael'

Hello Helen
Bonjour Henderson
Hola Michael


In [38]:
# sort 'string' and 'number'
def sort_num_list_1(num_list):
    list1.sort()
    return list1

def sort_num_list_2(num_list):
    list1.sort(key=int)
    return list1

In [43]:
list1=["1","10","3","22","23","4","2","200"]

print sort_num_list_1(list1)
print sort_num_list_2(list1)

['1', '10', '2', '200', '22', '23', '3', '4']
['1', '2', '3', '4', '10', '22', '23', '200']


In [46]:
list1=["c","cat","cut","ant","a","and","or","o", "oral"]

print sort_num_list_1(list1)

['a', 'and', 'ant', 'c', 'cat', 'cut', 'o', 'or', 'oral']


## Sort

In [118]:
# sort in list

a = [1,2,5,2,3]

a.sort()
print a
print sorted(a)

[1, 2, 2, 3, 5]
[1, 2, 2, 3, 5]


## Key Functions
Starting with Python 2.4, both 'list.sort()' and 'sorted()' added a 'key' parameter to  
specify a function to be called on each list element prior to makin comparions.  

In [56]:
print sorted("This is a test string from Andrew".split())
print sorted("This is a test string from Andrew".split(), key=str.lower)

['Andrew', 'This', 'a', 'from', 'is', 'string', 'test']
['a', 'Andrew', 'from', 'is', 'string', 'test', 'This']


In [60]:
string = "This is a test string from Andrew".split()
string.sort()
print string

string.sort(key=str.lower)
print string

['Andrew', 'This', 'a', 'from', 'is', 'string', 'test']
['a', 'Andrew', 'from', 'is', 'string', 'test', 'This']


In [66]:
string = ['andrew', 'Andrew', 'a', 'A']
string.sort()
print string

string.sort(key=str.lower)
print string

string.sort(key=str.upper)
print string

['A', 'Andrew', 'a', 'andrew']
['A', 'a', 'Andrew', 'andrew']
['A', 'a', 'Andrew', 'andrew']


In [73]:
# Ascending and Descending
string = "This is a test string from Andrew".split()
print sorted(string)
print sorted(string, reverse=True)

['Andrew', 'This', 'a', 'from', 'is', 'string', 'test']
['test', 'string', 'is', 'from', 'a', 'This', 'Andrew']


In [80]:
string = "2 4 5 20 5 3 50 52 4".split()
print sorted(string)
print sorted(string, key=int)

['2', '20', '3', '4', '4', '5', '5', '50', '52']
['2', '3', '4', '4', '5', '5', '20', '50', '52']


In [82]:
string = "2.0 4 5.0 20.2 5.01 3.1 50 52 30.0 4".split()
print sorted(string)
print sorted(string, key=int)

['2.0', '20.2', '3.1', '30.0', '4', '4', '5.0', '5.01', '50', '52']


ValueError: invalid literal for int() with base 10: '2.0'

In [83]:
string = "2.0 4 5.0 20.2 5.01 3.1 50 52 30.0 4".split()
print sorted(string)
print sorted(string, key=float)

['2.0', '20.2', '3.1', '30.0', '4', '4', '5.0', '5.01', '50', '52']
['2.0', '3.1', '4', '4', '5.0', '5.01', '20.2', '30.0', '50', '52']


In [86]:
string = "2.0 4 5.0 20.2 5.01 3.1 50 52 30.0 4".split()
print sorted(string)
print sorted(string, key=float)
print sorted(string, key=float, reverse=True)

['2.0', '20.2', '3.1', '30.0', '4', '4', '5.0', '5.01', '50', '52']
['2.0', '3.1', '4', '4', '5.0', '5.01', '20.2', '30.0', '50', '52']
['52', '50', '30.0', '20.2', '5.01', '5.0', '4', '4', '3.1', '2.0']


In [96]:
string = [[4,2,8],[2,4,3],[5,3,1]]
print sorted(string)
print 

string1 = sorted(string)
for st in string1:
    print sorted(st)

[[2, 4, 3], [4, 2, 8], [5, 3, 1]]

[2, 3, 4]
[2, 4, 8]
[1, 3, 5]


In [107]:
# sort in tuple

# tuple
# ('name','class','age')
student_tuples = [
    ('john','A',15),
    ('jane','B',12),
    ('jame','B',13)
]

In [108]:
sorted(student_tuples)

[('jame', 'B', 13), ('jane', 'B', 12), ('john', 'A', 15)]

In [111]:
# sort by student_tuples[0] = 'name'

sorted(student_tuples, key=lambda student_tuples: student_tuples[0])

[('jame', 'B', 13), ('jane', 'B', 12), ('john', 'A', 15)]

In [112]:
# sort by student_tuples[0] = 'class'

sorted(student_tuples, key=lambda student_tuples: student_tuples[1])

[('john', 'A', 15), ('jane', 'B', 12), ('jame', 'B', 13)]

In [113]:
# sort by student_tuples[0] = 'age'

sorted(student_tuples, key=lambda student_tuples: student_tuples[2])

[('jane', 'B', 12), ('jame', 'B', 13), ('john', 'A', 15)]

In [116]:
print sorted(student_tuples)
print sorted(student_tuples, reverse=True)

[('jame', 'B', 13), ('jane', 'B', 12), ('john', 'A', 15)]
[('john', 'A', 15), ('jane', 'B', 12), ('jame', 'B', 13)]


In [122]:
# sort in numpy array

import numpy as np

x = np.array([2,3,4,1,0,24,6,21,31])

In [123]:
sorted(x)

[0, 1, 2, 3, 4, 6, 21, 24, 31]

In [124]:
sorted(x,reverse=True)

[31, 24, 21, 6, 4, 3, 2, 1, 0]

In [128]:
print sorted(x)
print sorted(x,key=int)
print sorted(x,key=float)

[0, 1, 2, 3, 4, 6, 21, 24, 31]
[0, 1, 2, 3, 4, 6, 21, 24, 31]
[0, 1, 2, 3, 4, 6, 21, 24, 31]


In [154]:
import numpy as np

x = np.array([[6,1,6],[5,1,7],[7,6,8]])

In [155]:
sorted(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [156]:
print 'x\n', x
print

print 'sort'
print np.sort(x)
print 

print 'axis=None'
print np.sort(x, axis=None)
print 

print 'axis=0'
print np.sort(x, axis=0)
print

print 'axis=1'
print np.sort(x, axis=1)
print

x
[[6 1 6]
 [5 1 7]
 [7 6 8]]

sort
[[1 6 6]
 [1 5 7]
 [6 7 8]]

axis=None
[1 1 5 6 6 6 7 7 8]

axis=0
[[5 1 6]
 [6 1 7]
 [7 6 8]]

axis=1
[[1 6 6]
 [1 5 7]
 [6 7 8]]



# Structed array

In [159]:
dtype = [('name', 'S10'),('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahd', 1.7, 38)]

# create a structured array
name_list = np.array(values, dtype=dtype)

In [163]:
print 'type', type(name_list)
print
print name_list

type <type 'numpy.ndarray'>

[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahd', 1.7, 38)]


In [164]:
np.sort(name_list)

array([('Arthur', 1.8, 41), ('Galahd', 1.7, 38), ('Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [165]:
np.sort(name_list, order='name')

array([('Arthur', 1.8, 41), ('Galahd', 1.7, 38), ('Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [166]:
np.sort(name_list, order='age')

array([('Galahd', 1.7, 38), ('Lancelot', 1.9, 38), ('Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [169]:
print np.sort(name_list, order='height')

[('Galahd', 1.7, 38) ('Arthur', 1.8, 41) ('Lancelot', 1.9, 38)]


In [171]:
# sort by 'age', then 'height' if ages are equal

print np.sort(name_list, order=['age','height'])

[('Galahd', 1.7, 38) ('Lancelot', 1.9, 38) ('Arthur', 1.8, 41)]


In [180]:
print name_list
print '[0 1 2]'
print

print np.sort(name_list)
print np.argsort(name_list)

[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahd', 1.7, 38)]
[0 1 2]

[('Arthur', 1.8, 41) ('Galahd', 1.7, 38) ('Lancelot', 1.9, 38)]
[0 2 1]


# Example

In [193]:
list1 = raw_input('Enter values separated by spaces: ')

# this way you can avoid an user error while input a number (* accept only integer number)
try:
    list1 =[int(x) for x in list1.split()]     # int(x) = only integer value
    print 'sort: ', sorted(list1, key=int)
except ValueError:
    print 'None-integers in input!'

Enter values separated by spaces: 0.2 4
None-integers in input!


# Return Multiple values

In [30]:
def find_min_max(list_num):
    print list_num
    max_num = max(list_num)
    min_num = min(list_num)
    return max_num, min_num

In [31]:
list_num = [0,2,5,7,2,3]
maxx, minn = find_min_max(list_num)
print 'maxx: ', maxx, ', minn: ', minn

[0, 2, 5, 7, 2, 3]
maxx:  7 , minn:  0


In [32]:
max_num, min_num = find_min_max(['output', 'input', 'i/o'])
print 'max: ', max_num, ', min: ', min_num

['output', 'input', 'i/o']
max:  output , min:  i/o


# Multiple parameters / arguments

### we can define more than one parameter in the function definition
### we match the number and order of arguments and parameters

In [82]:
def addtwo(a, b):
    added = a+b
    return added

x = addtwo(3, 5)
print x

8


In [84]:
def addtwo(a, b):
    return a+b

print addtwo(3, 5)

8


In [96]:
def printinfo(name, age):   
   print "Name: ", name
   print "Age ", age
   return;

printinfo(age=50, name="miki")
print

printinfo(50, "miki")

Name:  miki
Age  50

Name:  50
Age  miki


# Void (non-fruitful) functions

### When a function does not return a value, we call it a 'void' function
### Functions that return values are 'fruitful' functions
### 'Void' functions are 'not fruitful'

# exercise  

Create a function that use to convert a degree Celsius to Fahrenheit and Fahrenheit to Celsius  

```
equation: Fahrenheit to Celsius
    (F - 32) * (5/9) = C  
   
equation: Celsius to Fahrenheit
    (C * (9/5)) + 32 = F
    
where 
    F = Fahrenheit  
    C = Celsius      
```



In [87]:
EURO_TO_DOLLAR = 0.72 # Exchange rate on April 22, 2014
dollars = raw_input("How many Dollars do you wish to convert to Euros? :")
try:
    dollars = float(dollars)
except ValueError:
    print dollars, "is not a number!"
else:
    print dollars, "dollars =", dollars * EURO_TO_DOLLAR
    print "euros"
print "Thank you!"

How many Dollars do you wish to convert to Euros? :10.2
10.2 dollars = 7.344
euros
Thank you!


# a function with optional parameters

In [88]:
def addtwo(a, b=5):
    added = a+b
    return added

print addtwo(3, 5)
print addtwo(3)

8
8


# Global constants

### If you define global variables, they are visible inside all of your functions.

In [92]:
PI = 3.14159265358979   # global constant -- only place the value of PI is set

def circleArea(radius):
    return PI*radius*radius    # use value of global constant PI

def circleCircumference(radius):
    return 2*PI*radius         # use value of global constant PI

print('circle area with radius 5:', circleArea(5))
print('circumference with radius 5:', circleCircumference(5))

('circle area with radius 5:', 78.53981633974475)
('circumference with radius 5:', 31.4159265358979)


# Main function

In [98]:
def main():  
  print("This is a main function")

main()

This is a main function


In [99]:
def main():
  print("This is a main function")
  
# Execute `main()` function 
if __name__ == '__main__':
    main()

This is a main function


# Nested functions
### Nested functions are functions defined within other functions.

In [104]:
def outside():
    outsideList = [1, 2]
    def nested():
        outsideList.append(3)
    nested()
    print outsideList

outside()

[1, 2, 3]


In [107]:
def outside():
    def nested():
        outsideList.append(3)
    outsideList = [1, 2]
    nested()
    print outsideList

outside()

[1, 2, 3]


In [116]:
def factorial(number):

    # error handling
    if not isinstance(number, int):
        raise TypeError("Sorry. 'number' must be an integer.")
    if not number >= 0:
        raise ValueError("Sorry. 'number' must be zero or positive.")

    def inner_factorial(number):
        if number <= 1:
            return 1
        return number*inner_factorial(number-1)
    return inner_factorial(number)

# call the outer function
print(factorial(3))

6


In [122]:
print isinstance(5, int)
print isinstance(5.0, int)
print 

print isinstance(5.0, float)
print isinstance(5, float)

True
False

True
False


# Docstring

### The first statement in the body of a function is usually a string, which can be accessed with 
```
functionname.__doc__   
```

In [223]:
def Hello():
    """ Greet a person! """

Hello.__doc__

' Greet a person! '

In [225]:
def add_number(a, b):
    """adding numbers a and b  
    
    """

In [226]:
add_number.__doc__

'adding numbers a and b  \n    \n    '

In [215]:
def function_with_types_in_docstring(param1, param2):
    """Example function with types documented in the docstring.

    `PEP 484`_ type annotations are supported. If attribute, parameter, and
    return types are annotated according to `PEP 484`_, they do not need to be
    included in the docstring:

    Args:
        param1 (int): The first parameter.
        param2 (str): The second parameter.

    Returns:
        bool: The return value. True for success, False otherwise.

    .. _PEP 484:
        https://www.python.org/dev/peps/pep-0484/

    """

In [227]:
function_with_types_in_docstring.__doc__

'Example function with types documented in the docstring.\n\n    `PEP 484`_ type annotations are supported. If attribute, parameter, and\n    return types are annotated according to `PEP 484`_, they do not need to be\n    included in the docstring:\n\n    Args:\n        param1 (int): The first parameter.\n        param2 (str): The second parameter.\n\n    Returns:\n        bool: The return value. True for success, False otherwise.\n\n    .. _PEP 484:\n        https://www.python.org/dev/peps/pep-0484/\n\n    '

In [228]:
print function_with_types_in_docstring.__doc__

Example function with types documented in the docstring.

    `PEP 484`_ type annotations are supported. If attribute, parameter, and
    return types are annotated according to `PEP 484`_, they do not need to be
    included in the docstring:

    Args:
        param1 (int): The first parameter.
        param2 (str): The second parameter.

    Returns:
        bool: The return value. True for success, False otherwise.

    .. _PEP 484:
        https://www.python.org/dev/peps/pep-0484/

    


In [230]:
help(function_with_types_in_docstring)

Help on function function_with_types_in_docstring in module __main__:

function_with_types_in_docstring(param1, param2)
    Example function with types documented in the docstring.
    
    `PEP 484`_ type annotations are supported. If attribute, parameter, and
    return types are annotated according to `PEP 484`_, they do not need to be
    included in the docstring:
    
    Args:
        param1 (int): The first parameter.
        param2 (str): The second parameter.
    
    Returns:
        bool: The return value. True for success, False otherwise.
    
    .. _PEP 484:
        https://www.python.org/dev/peps/pep-0484/

