# Numpy Array
## ndarray

In [1]:
# การเรียกใช้งาน
import numpy as np

In [2]:
# การสร้าง array 1 มิติ

x = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
# การดู properties ของ array

# ดูขนาดของ array
print x.shape

# ดูประเภทของ
print type(x)

# ดูประเภทของ data-type
print x.dtype

(10,)
<type 'numpy.ndarray'>
int64


## Array indexing 
### สำหรับ array 1 มิติ

In [4]:
# เข้าถึงข้อมูล (access) ใน array

print x[0] #index แรก
print x[-1] #index สุดท้าย
print 

print x[:] #ข้อมูลทุกตัว
print x[0:]
print

print x[0::2] #แสดงตั้งแต่ index ที่ 0 และแสดงทุกๆ 2 ลำดับ
print x[1::2] #แสดงตั้งแต่ index ที่ 1 และแสดงทุกๆ 2 ลำดับ
print x[1::3] #แสดงตั้งแต่ index ที่ 1 และแสดงทุกๆ 3 ลำดับ
print 

print x[0:5] #แสดงตั้งแต่ตัวที่ 0 จนถึงตัวที่ 5-1
print x[1:5] #แสดงตั้งแต่ตัวที่ 1 จนถึงตัวที่ 5-1
print x[0:-1] #แสดงตั้งแต่ตัวที่ 0 จนถึงตัวสุดท้าย-1

0
9

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]

[0 2 4 6 8]
[1 3 5 7 9]
[1 4 7]

[0 1 2 3 4]
[1 2 3 4]
[0 1 2 3 4 5 6 7 8]


In [5]:
# เก็บข้อมูลที่เป็น float
x = np.array([2,3,1.0,0.5])

print x.dtype

float64


## แสดงข้อมูลใน Array ด้วย For Loop 

In [6]:
print x, "\n"

for i in x:
    print i

[2.  3.  1.  0.5] 

2.0
3.0
1.0
0.5


In [7]:
print x, "\n"

# ดูขนาดของ array
print "shape", x.shape

shape = x.shape[0]
print "shape", shape, "\n"

for i in range(0,shape):
    print x[i]

[2.  3.  1.  0.5] 

shape (4,)
shape 4 

2.0
3.0
1.0
0.5


## แสดงข้อมูลใน Array ด้วย While Loop 

In [8]:
print x, "\n"

shape = x.shape[0]
print "shape", shape, "\n"

count = 0
while (count < shape):
    print "x[",count,"] = ", x[count]
    count=count+1    # count = count+1

[2.  3.  1.  0.5] 

shape 4 

x[ 0 ] =  2.0
x[ 1 ] =  3.0
x[ 2 ] =  1.0
x[ 3 ] =  0.5


## data type 

In [9]:
# ข้อควรระวังในการกำหนด data type ของ array
x = np.array([124,125,126,127,128,129,130,131,132], dtype='int8')

print x
print x.dtype
print

# ไม่กำหนด data type
x = np.array([124,125,126,127,128,129,130,131,132])

print x
print x.dtype

[ 124  125  126  127 -128 -127 -126 -125 -124]
int8

[124 125 126 127 128 129 130 131 132]
int64


In [10]:
x = np.array([124,125,126,127,128,129,130,131,132], dtype='int64')

print x

[124 125 126 127 128 129 130 131 132]


In [11]:
# ข้อมูลที่ป้อนลงไปเป็น float แต่จะจัดเก็บเป็น int
x = np.array([124.5,125.6,126.0,127.1,128,129,130,131,132], dtype='int64')

print x
print

x = np.array([124.512,125.6,126.0,127.1,128,129,130,131,132], dtype='float64')

print x

[124 125 126 127 128 129 130 131 132]

[124.512 125.6   126.    127.1   128.    129.    130.    131.    132.   ]


## สร้าง Array เปล่า

In [12]:
# สร้าง Array แบบ 1 มิติ โดยมีขนาด 2row x 4col
# และกำหนดให้ข้อมูลที่อยู่ใน array มีค่าเป็น 0
x = np.zeros((2,4))
print x
print x.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [13]:
# สร้าง Array แบบ 1 มิติ โดยมีขนาด 2row x 4col
# และกำหนดให้ข้อมูลที่อยู่ใน array มีค่าเป็น 1
x = np.ones((2,4), dtype='int8')
print x
print x.dtype

[[1 1 1 1]
 [1 1 1 1]]
int8


In [14]:
#!/usr/bin/python
# -*- coding: utf-8 -*-

str = u'โอฬาริก'

print str, "\n"

for i in str:
    print i

print    
for i in str:
    print " ", i

print
print "str[0] ", str[0]
print "str[1] ", str[1]

โอฬาริก 

โ
อ
ฬ
า
ร
ิ
ก

  โ
  อ
  ฬ
  า
  ร
  ิ
  ก

str[0]  โ
str[1]  อ


# 2D Array
## Array 2 มิติ

In [15]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])

print x
print "\nshape", x.shape

[[0 1 2]
 [3 4 5]
 [6 7 8]]

shape (3, 3)


In [16]:
print x[0,0], x[0,1], x[0,2]
print x[1,0], x[1,1], x[1,2]
print x[2,0], x[2,1], x[2,2]

0 1 2
3 4 5
6 7 8


In [17]:
for i in x:
    print i

[0 1 2]
[3 4 5]
[6 7 8]


In [18]:
for i in range(0, x.shape[0]):
    for j in range(0, x.shape[1]):
        print x[i,j],
    print 

0 1 2
3 4 5
6 7 8


# Assign new values in an array 

In [19]:
x[0,0] = 100
x[0,1] = 200
x[0,2] = 300

print x

[[100 200 300]
 [  3   4   5]
 [  6   7   8]]


In [20]:
x = np.zeros((5,5), dtype='int8')
y = np.array([[2,2,2],[3,3,3],[4,4,4]])

print x
print
print y

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [21]:
# copy ข้อมูลจาก y ไปไว้ใน X
x[0:3,0:3] = y

print x

[[2 2 2 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Sum of array elements 

In [22]:
print "vertical summantion", x.sum(axis=0)
print "Horizontal summantion", x.sum(axis=1)
print "Summation", x.sum()

vertical summantion [9 9 9 0 0]
Horizontal summantion [ 6  9 12  0  0]
Summation 27


## Reshape

In [23]:
#x = np.zeros((2,8))
x = np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15]])
print x.shape
print x

(2, 8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [24]:
y = x.reshape((8,2))
print y.shape
print y

(8, 2)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [25]:
y = x.reshape((4,4))
print y.shape
print y

(4, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
y = x.reshape((1,16))
print y.shape
print y

(1, 16)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


# 3D Array

### ตัวอย่าง
สร้าง Array ขนาด (4x5) จำนวน 3 Layer/Dimension  
  
กำหนด Array ดังนี้ (3,4,5)  
ดังนั้น  
3 = 3 Layer/Dimenstion  
4 = 4 row  
5 = 5 col

In [27]:
x = np.zeros((3,4,5))
print x.shape
print x

(3, 4, 5)
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [28]:
# กำหนดให้ y เป็น array 2 มิติ ที่มีขนาด 4x5
y = np.ones((4,5))
print y

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [29]:
#Assign new values in an array

# กำหนดให้ X ที่ Layer = 0 ทุก Row (:) และ ทุก Col (:) มีค่าเท่ากับ y
x[0,:,:] = y
print x

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [30]:
# show array elements

# แสดงข้อมูลของ X จาก Layer 0
x[0]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# แสดงข้อมูลของ X จาก Layer 0
x[0,:,:]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# แสดงข้อมูลของ X ทุกๆ Layer ใน row (0:2) และ col (0:2)
x[:,0:2,0:2]

array([[[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [33]:
print x.shape

(3, 4, 5)


In [34]:
y = x.reshape((1,2,30))
print y.shape
print y

(1, 2, 30)
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0.]]]
